### ISSUE TITLE
Allow me to delete the first character of the deck

### ISSUE THREAD

**Issue by iopq** [TanayB11/jadeocr-next#108]
I haven't figured out how to delete the character 一 since it literally never gets detected right (unless i write a perfectly straight line), but it's the first one I added in my deck. I can't reorder it and I can't delete it without deleting the whole deck.

I'd like deletion to have a checkbox for which item(s) you want removed, not just deleting the last thing

**Comment by TanayB11** [comment]
You can delete any character in a deck by simply clearing the fields (or just deleting the character) in its corresponding row. Upon saving, the character will be removed from the deck.
